name: Scheduled Cloud end-to-end tests

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  playwright-cloud:
    uses: grafana/data-sources-ci-workflows/.github/workflows/playwright-cloud.yml@51ac69d43a199cee552c96fc184f15d64ea75892 # main
    secrets: inherit
    with:
      repo-secrets: |
        DS_INSTANCE_HOST=grafana-postgresql-datasource/instance:host
        DS_INSTANCE_PASSWORD=grafana-postgresql-datasource/instance:password
        DS_INSTANCE_PORT=grafana-postgresql-datasource/instance:port
        DS_INSTANCE_USERNAME=grafana-postgresql-datasource/instance:username
